import { S3Client, PutObjectCommand, GetObjectCommand, HeadObjectCommand } from '@aws-sdk/client-s3'
import { getSignedUrl } from '@aws-sdk/s3-request-presigner'

// Railway S3-compatible storage configuration
const ENDPOINT = process.env.S3_ENDPOINT || process.env.AWS_ENDPOINT_URL
const REGION = process.env.AWS_REGION || process.env.AWS_DEFAULT_REGION || 'auto'
const BUCKET = process.env.S3_BUCKET || process.env.AWS_S3_BUCKET || process.env.AWS_S3_BUCKET_NAME || process.env.RAILWAY_BUCKET_NAME
const ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID
const SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY

let client: S3Client | null = null
if (BUCKET && ACCESS_KEY_ID && SECRET_ACCESS_KEY) {
  const config: any = {
    region: REGION,
    credentials: {
      accessKeyId: ACCESS_KEY_ID,
      secretAccessKey: SECRET_ACCESS_KEY,
    },
  }

  // For Railway S3-compatible storage (or any non-AWS S3)
  if (ENDPOINT) {
    config.endpoint = ENDPOINT
    config.forcePathStyle = true // Required for non-AWS S3-compatible storage
  }

  client = new S3Client(config)
}

/** Returns true when S3 is properly configured and uploads will go to S3. */
export function isS3Configured(): boolean {
  return Boolean(client && BUCKET)
}

/**
 * Upload a file buffer to S3-compatible storage.
 * Returns null if S3 is not configured.
 */
export async function uploadBufferToS3(
  buffer: Buffer,
  key: string,
  contentType = 'application/octet-stream',
): Promise<string | null> {
  if (!client || !BUCKET) return null

  // Upload WITHOUT ACL - Railway S3 doesn't support public-read ACL.
  // Access is via signed URLs generated by getSignedMediaUrl().
  const cmd = new PutObjectCommand({
    Bucket: BUCKET,
    Key: key,
    Body: buffer,
    ContentType: contentType,
  })

  await client.send(cmd)

  // Return just the key - callers should use /api/media/serve/[key] for access
  return key
}

/**
 * Generate a temporary signed URL for a private S3 object.
 * Default expiry: 1 hour.
 * Use this instead of any public URL when the bucket is private (Railway).
 */
export async function getSignedMediaUrl(
  key: string,
  expiresIn = 3600,
): Promise<string | null> {
  if (!client || !BUCKET) return null

  const cmd = new GetObjectCommand({
    Bucket: BUCKET,
    Key: key,
  })

  return await getSignedUrl(client, cmd, { expiresIn })
}

/** True if an object exists in the configured private bucket (for HEAD checks). */
export async function mediaExistsInS3(key: string): Promise<boolean> {
  if (!client || !BUCKET) return false
  try {
    await client.send(new HeadObjectCommand({ Bucket: BUCKET, Key: key }))
    return true
  } catch {
    return false
  }
}

export type PrivateMediaStreamResult = {
  body: ReadableStream<Uint8Array> | Uint8Array
  contentType: string
}

/**
 * Read an object from the private bucket for same-origin streaming.
 * Avoids redirecting browsers to signed URLs (which often violate CSP `img-src`).
 */
export async function getPrivateMediaBody(key: string): Promise<PrivateMediaStreamResult | null> {
  if (!client || !BUCKET) return null

  try {
    const result = await client.send(
      new GetObjectCommand({
        Bucket: BUCKET,
        Key: key,
      }),
    )

    const contentType = result.ContentType || 'application/octet-stream'
    type SdkBody = {
      transformToWebStream?: () => ReadableStream<Uint8Array>
      transformToByteArray?: () => Promise<Uint8Array>
    }
    const rawBody = result.Body as SdkBody | undefined
    if (!rawBody) return null

    if (typeof rawBody.transformToWebStream === 'function') {
      return { body: rawBody.transformToWebStream(), contentType }
    }

    const bytes =
      typeof rawBody.transformToByteArray === 'function' ? await rawBody.transformToByteArray() : undefined

    if (bytes && bytes.byteLength > 0) {
      return { body: bytes, contentType }
    }

    return null
  } catch (err) {
    console.warn('[getPrivateMediaBody]', key, err)
    return null
  }
}
